ALTER TABLE usuario 
ALTER COLUMN rua DROP NOT NULL,
ALTER COLUMN numero DROP NOT NULL,
ALTER COLUMN bairro DROP NOT NULL,
ALTER COLUMN complemento DROP NOT NULL,
ALTER COLUMN cidade DROP NOT NULL,
ALTER COLUMN uf DROP NOT NULL;
